# Generated by Django 5.1.4 on 2025-01-26 16:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_app', '0002_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
